'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { CalendarDays, List } from 'lucide-react';
import DashboardLayout from '@/components/layout/DashboardLayout';
import { useAuth } from '@/context/AuthContext';
import { useToast } from '@/context/ToastContext';

interface Appointment { _id: string; serviceType: string; dateTime: string; duration: number; status: string; notes?: string; price: number; petId?: { name: string; species: string }; ownerId?: { name: string; email: string } }

export default function ProviderAppointmentsPage() {
  const { token } = useAuth(); const { showToast } = useToast();
  const [appointments, setAppointments] = useState<Appointment[]>([]); const [activeTab, setActiveTab] = useState('pending'); const [view, setView] = useState<'list' | 'calendar'>('list'); const [loading, setLoading] = useState(true);
  const [proposingId, setProposingId] = useState(''); const [proposedDate, setProposedDate] = useState('');
  // The API derives the provider identity from the token, so no provider ID is trusted from the browser.
  const load = useCallback(async () => { if (!token) return; const response = await fetch('/api/appointments', { headers: { Authorization: `Bearer ${token}` } }); const data = await response.json(); setAppointments(data.appointments || []); setLoading(false); }, [token]);
  useEffect(() => { void load(); }, [load]);
  // All status transitions are validated again on the server before they are persisted.
  const updateStatus = async (id: string, status: string, newDateTime?: string) => { const response = await fetch(`/api/appointments/${id}/status`, { method: 'PATCH', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify({ status, newDateTime: newDateTime ? new Date(newDateTime).toISOString() : undefined }) }); const data = await response.json(); if (!response.ok) return showToast(data.error || 'Unable to update appointment', 'error'); showToast(data.message, 'success'); setProposingId(''); setProposedDate(''); await load(); };
  const filtered = appointments.filter(appointment => appointment.status === activeTab);
  // Calendar mode groups actionable appointments by their ISO date.
  const byDate = useMemo(() => appointments.filter(appointment => ['pending', 'confirmed', 'rescheduled'].includes(appointment.status)).reduce<Record<string, Appointment[]>>((groups, appointment) => { const key = new Date(appointment.dateTime).toISOString().slice(0, 10); (groups[key] ||= []).push(appointment); return groups; }, {}), [appointments]);

  const card = (appointment: Appointment) => <article key={appointment._id} className="card" style={{ padding: 16, display: 'grid', gap: 9 }}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 12 }}><div><strong style={{ textTransform: 'capitalize' }}>{appointment.serviceType}</strong><p style={{ color: 'var(--text-secondary)', fontSize: 13 }}>{appointment.petId?.name || 'Pet'} · {appointment.ownerId?.name || 'Client'}</p></div><span className={`badge ${appointment.status === 'confirmed' ? 'badge-blue' : appointment.status === 'completed' ? 'badge-green' : appointment.status === 'cancelled' ? 'badge-red' : 'badge-orange'}`}>{appointment.status}</span></div><p style={{ fontSize: 13 }}>{new Date(appointment.dateTime).toLocaleString()} · {appointment.duration} min · Rs. {(appointment.price || 0).toLocaleString()}</p>{appointment.notes && <p style={{ fontSize: 12, color: 'var(--text-muted)' }}>{appointment.notes}</p>}{appointment.status === 'rescheduled' && <p style={{ fontSize: 12, color: 'var(--text-secondary)' }}>Waiting for the pet owner to accept the proposed time.</p>}<div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>{appointment.status === 'pending' && <><button className="btn btn-primary btn-sm" onClick={() => void updateStatus(appointment._id, 'confirmed')}>Accept</button><button className="btn btn-secondary btn-sm" onClick={() => setProposingId(appointment._id)}>Propose time</button><button className="btn btn-danger btn-sm" onClick={() => void updateStatus(appointment._id, 'cancelled')}>Decline</button></>}{appointment.status === 'confirmed' && <button className="btn btn-primary btn-sm" onClick={() => void updateStatus(appointment._id, 'completed')}>Mark complete</button>}</div>{proposingId === appointment._id && <div style={{ display: 'flex', gap: 8 }}><input className="input" type="datetime-local" value={proposedDate} onChange={event => setProposedDate(event.target.value)} /><button className="btn btn-primary btn-sm" disabled={!proposedDate} onClick={() => void updateStatus(appointment._id, 'rescheduled', proposedDate)}>Send proposal</button></div>}</article>;

  return <DashboardLayout><div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 20 }}><div><h1 className="page-title">Appointments</h1><p className="page-subtitle">Booking requests, calendar and appointment actions</p></div><div style={{ display: 'flex', gap: 4 }}><button className={`btn ${view === 'list' ? 'btn-primary' : 'btn-secondary'}`} onClick={() => setView('list')}><List size={16} /> List</button><button className={`btn ${view === 'calendar' ? 'btn-primary' : 'btn-secondary'}`} onClick={() => setView('calendar')}><CalendarDays size={16} /> Calendar</button></div></div>
    {view === 'list' ? <><div style={{ display: 'flex', gap: 5, marginBottom: 18 }}>{['pending', 'confirmed', 'completed', 'cancelled', 'rescheduled'].map(tab => <button key={tab} className={`btn btn-sm ${activeTab === tab ? 'btn-primary' : 'btn-secondary'}`} onClick={() => setActiveTab(tab)}>{tab} ({appointments.filter(item => item.status === tab).length})</button>)}</div>{loading ? <div className="skeleton" style={{ height: 100 }} /> : <div style={{ display: 'grid', gap: 11 }}>{filtered.map(card)}{filtered.length === 0 && <div className="empty-state"><p>No {activeTab} appointments.</p></div>}</div>}</> : <div style={{ display: 'grid', gap: 16 }}>{Object.entries(byDate).sort(([a], [b]) => a.localeCompare(b)).map(([date, items]) => <section key={date}><h2 style={{ fontSize: 15, marginBottom: 8 }}>{new Date(`${date}T00:00:00`).toLocaleDateString([], { weekday: 'long', month: 'long', day: 'numeric' })}</h2><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: 10 }}>{items.map(card)}</div></section>)}</div>}
  </DashboardLayout>;
}
