import { NextRequest, NextResponse } from 'next/server';
import connectDB from '@/lib/db';
import HealthRecord from '@/models/HealthRecord';
import Pet from '@/models/Pet';
import { verifyToken } from '@/lib/jwt';

function getUserFromRequest(req: NextRequest) {
  const authHeader = req.headers.get('authorization');
  if (!authHeader || !authHeader.startsWith('Bearer ')) return null;
  const token = authHeader.split(' ')[1];
  return verifyToken(token);
}

// GET /api/health-records/[id]/download
export async function GET(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  try {
    await connectDB();
    const user = getUserFromRequest(req);
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

    const { id } = await params;
    const record = await HealthRecord.findOne({
      _id: id,
      ownerId: user.userId,
    });

    if (!record) return NextResponse.json({ error: 'Health record not found' }, { status: 404 });

    const pet = await Pet.findById(record.petId);

    // Generate a simple HTML report that the browser can print as PDF
    const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>Health Record - ${pet?.name || 'Pet'}</title>
        <style>
          body { font-family: Arial, sans-serif; max-width: 800px; margin: 40px auto; color: #333; }
          h1 { color: #1D9E75; border-bottom: 2px solid #1D9E75; padding-bottom: 10px; }
          h2 { color: #378ADD; margin-top: 24px; }
          .label { font-weight: bold; color: #555; }
          .value { margin-bottom: 12px; }
          .footer { margin-top: 40px; font-size: 12px; color: #999; border-top: 1px solid #eee; padding-top: 10px; }
        </style>
      </head>
      <body>
        <h1>PawSync Health Record 🐾</h1>
        <h2>Pet Information</h2>
        <p class="label">Pet Name:</p>
        <p class="value">${pet?.name || 'Unknown'}</p>
        <p class="label">Species:</p>
        <p class="value">${pet?.species || 'Unknown'}</p>
        <p class="label">Breed:</p>
        <p class="value">${pet?.breed || 'Unknown'}</p>

        <h2>Health Record Details</h2>
        <p class="label">Date:</p>
        <p class="value">${new Date(record.date).toDateString()}</p>
        <p class="label">Diagnosis:</p>
        <p class="value">${record.diagnosis || 'None recorded'}</p>
        <p class="label">Treatment:</p>
        <p class="value">${record.treatment || 'None recorded'}</p>
        <p class="label">Prescriptions:</p>
        <p class="value">${record.prescriptions?.join(', ') || 'None'}</p>
        <p class="label">Record Version:</p>
        <p class="value">${record.version}</p>

        <div class="footer">
          Generated by PawSync on ${new Date().toDateString()} | Record ID: ${record._id}
        </div>
      </body>
      </html>
    `;

    return new NextResponse(html, {
      headers: {
        'Content-Type': 'text/html',
        'Content-Disposition': `attachment; filename="health-record-${id}.html"`,
      },
    });
  } catch (error) {
    console.error('Download health record error:', error);
    return NextResponse.json({ error: 'Something went wrong' }, { status: 500 });
  }
}